tdex-network/tdex-dashboard

- src/features/operator/Market/MarketWithdraw/index.tsx
- src/features/operator/TxsTable/DepositRows.tsx
- src/features/operator/TxsTable/TradeRows.tsx
- src/features/operator/TxsTable/WithdrawalRows.tsx
- src/utils/asset.ts
- src/utils/constants.ts
- src/utils/unitConvert.ts
In market withdraw, expect lbtc amount to be inputted in favorite user unit.
In table, display LBTC unit instead of hardcoded LBTC ticker.
> Fix lbtc unit

- src/features/operator/Fee/FeeDeposit/index.tsx
- src/features/operator/Market/MarketDeposit/index.tsx
- src/features/operator/operator.api.ts
In order to avoid error `Transaction Conflict. Please retry` given by getFeeFragmenterAddress when called at the same time of getFeeAddress.
Also add method names to error log.
> Skip get fragmenter address on component mounting 

- .gitignore
- rpc_proxy.go
- src/App.tsx
This adds cors headers to the response of proxy's HTTP endpoints /healthcheck and /connect.
Please @tiero @Janaka-Steph review this.
> Add cors headers to http endpoint responses

- rpc_proxy.go
This fixes the codes of the statuses returned by the ` /healthcheck` endpoint of the proxy.
Closes #178.
Please @tiero @Janaka-Steph review this.
> Proxy: fix status codes

- src/App.tsx
- src/features/home/Home.tsx
- src/features/settings/Settings.tsx
- src/features/walletUnlocker/OnboardingPairing.tsx
- src/features/walletUnlocker/walletUnlocker.api.ts
- src/routes/index.tsx
Redirect to CreateOrRestore page if paired with not initialized daemon, based on isReady response.
User can still nagivate to pairing page using the breadcrumb if he wants to.
It closes #86 
> Redirect to CreateOrRestore if paired with not init daemon

- src/App.tsx
To avoid rehydration issues we make sure the only persisted state comes from filesystem.
> Remove localStorage before quitting

- src/App.tsx
- src/app/rootReducer.ts
- src/app/store.ts
- src/utils/storage.ts
Two PersistConfig where used, one produced by the `persist` in `src/utils/storage.ts` (the one used by Tauri FS) and the other in `src/app/store.ts` (also used in Tauri app as local storage).
This PR remove the use of `persist` function on the settings reducer. Instead we check if it's Tauri app and pass the proper PersistConfig.
> When on Tauri use tauriStorage only

- src/routes/index.tsx
This is to allow clearing cache when app crashes.
> Allow accessing Settings route even if daemon not ready

- src/assets/styles/button.less
- src/common/VolumeChart/index.tsx
- src/features/operator/Market/MarketOverview/VolumePanel.tsx
- src/features/operator/Market/MarketOverview/index.tsx
- src/features/operator/operator.api.ts
- Use predefined TimeRange/Timeframe combinations to simplify UI, not exposing TF to user
- 1D => TF 1H
- 7D => TF 4H
- 1M => TF 1D
- 3M => TF 1D
- 1Y => TF 1W (Waiting for https://github.com/tdex-network/tdex-daemon/issues/569)
- YTD => TF 1W
- ALL => TF 1W 
- Default timeRange when entering the page is 1M
> Volume chart

- src/domain/asset.ts
- src/features/home/DashboardPanelLeft.tsx
- src/features/home/DashboardPanelRight.tsx
- src/features/operator/Fee/FeeForm/index.tsx
- src/features/operator/Fee/FeeWithdraw/index.tsx
- src/features/operator/Market/MarketOverview/VolumePanel.tsx
- src/features/operator/Market/MarketWithdraw/index.tsx
- src/features/operator/TxsTable/AllRows.tsx
- src/features/operator/TxsTable/DepositRows.tsx
- src/features/operator/TxsTable/TradeRows.tsx
- src/features/operator/TxsTable/TxRow.tsx
- src/features/operator/TxsTable/WithdrawalRows.tsx
- src/features/operator/TxsTable/index.tsx
- src/utils/asset.ts
- src/utils/unitConvert.ts
- Rename `formatSatsToUnit` to `fromSatsToUnitOrFractional` and take into account asset precision
- `getAssetDataFromRegistry` returns Asset with a new `formattedTicker` property (either LBTC unit or ticker)
- We don't include `formattedTicker` in store to avoid complexity keeping the prop in sync when changing unit 
- `formattedTicker` is used when we want to display either the asset ticker or LBTC unit
- Used in `src/features/operator/TxsTable/index.tsx` to compute `baseAsset` and `quoteAsset`, passing them down to components and used by `fromSatsToUnitOrFractional`
It closes #292 
> Fix asset precision, refactoring

- src/common/VolumeChart/index.tsx
- src/features/operator/Market/MarketOverview/VolumePanel.tsx
Chart baseVolume values and Y-axis are converted to Lbtc unit or fractional (using asset precision only)
> [Chart] Convert baseVolume to Lbtc unit or fractional

- src/common/DepositPage/index.tsx
- src/features/operator/Fee/FeeForm/index.tsx
- src/features/operator/Market/CreateMarket/index.tsx
- src/features/operator/Market/ListMarkets/MarketListItem.tsx
- src/features/operator/Market/ListMarkets/index.tsx
- src/features/operator/Market/MarketOverview/index.tsx
- src/features/operator/Market/MarketWithdraw/index.tsx
It closes #285 
- Display collected swap fees, base and quote, in lbtc unit or fractional.
- Get asset data from `getAssetDataFromRegistry` to avoid network request and to use `formattedTicker` Asset property.
> [Market Overview] Display collected swap fees

- .github/workflows/main.yml
- src/utils/unitConvert.spec.ts
- src/utils/unitConvert.ts
It closes #299 
- `fromUnitToUnit` takes liquid bitcoin amount in certain unit and convert it to another unit
- use `toFixed()` instead of `toString()` to avoid scientific notation
- throw if amount is invalid
> Add fromUnitToUnit helper

- src-tauri/tauri.conf.json
Tauri launched with `yarn tauri:dev` doesn't kill dev server process.
This PR kills the previous dev server process at startup. Not ideal solution but it works. If no process is running on 3003 then the error is ignored.
Better solution would have been to kill the process when quitting. I tried this from Rust `Command::new("kill -9 $(lsof -i :3003 -t)");` but has no effect.
> Kill previous dev server process at start

- src/app/config.ts
- src/common/UserMenu/index.tsx
- src/features/settings/settingsSlice.ts
- Remove baseUrl from config file because this value should only be taken from PROXY_URL or extracted from tdexConnectUrl. We can't have a default value.
- reset all apis using the base api `tdexApi`
> Remove baseUrl from config file

- src/assets/styles/button.less
- src/features/home/DashboardPanelLeft.tsx
- src/features/home/dashboardPanelLeft.less
- src/features/operator/operator.api.ts
It closes #276 
- Request getMarketReport from start date `${new Date().getFullYear()}-01-01T00:00:00` until 24h ago 
- Request getMarketReport from start date `${new Date().getFullYear()}-01-01T00:00:00` until now
- For each report, convert baseAmount and quoteAmount to LBTC L-sats, then add them together.
- Finally we calculate percentage variation by doing `((totalCollectedSwapFeesUntilNow - totalCollectedSwapFeesUntil24hAgo) / totalCollectedSwapFeesUntil24hAgo) * 100`
> Calculate total earned percentage change

- src/App.tsx
- src/features/settings/settingsSlice.ts
- src/features/walletUnlocker/OnboardingPairing.tsx
Add `isTauri` in store and do not assume `isTauri` === `useProxy`.
To run the proxy in browser mode `window.USE_PROXY` needs to be set to true.
Blocker: `error connection refused`. Probably because proxy and daemon are not running in the same container.
> Add isTauri in store

- src/features/settings/settingsSlice.ts
Allow retrieving macaroon on Tauri.
> Fix "expected 1 macaroon, got 0" error on Tauri

- src/features/settings/settingsSlice.ts
Reverting https://github.com/tdex-network/tdex-dashboard/pull/389
Calling `await client.listMarkets(new ListMarketsRequest(), metadata)` with metadata `null` works.
Calling `await client.listMarkets(new ListMarketsRequest(), metadata)` with metadata `macaroon: xxx` we get `expected 1 macaroon, got 2`
> Fix `expected 1 macaroon, got 2` on Tauri

- src/features/operator/Market/MarketSettings/UpdateMarketPriceForm.tsx
In UpdateMarketPrice form btc input, the number of decimals depends on the unit. 
L-BTC == 8 decimals
L-mBTC == 5 decimals
L-bits == 3 decimals
L-sats == 0 decimals
Display error "Too many decimals" if error
> Display error "Too many decimals"

- src/App.tsx
- src/common/UserMenu/index.tsx
- src/routes/index.tsx
This fixes the connection of the proxy to the daemon after wallet initialization.
For this, the original effect in App.tsx starting and passing the connect URL to the proxy (via /connect endpoint) has been split into 2 different ones: 1 for starting up the proxy, and 1 for handling the connection based entirely on changes to `tdexdConnectUrl`.
By doing so, every time the connect URL changes in the store, ie. after creating/restoring a wallet, the dashboard provides to pass it down to the proxy. In case the connect URL is removed from the store (ie. logout), the dashboard takes care of calling proxy's `/disconnect` endpoint.
We now have a single point in the codebase where we handle the connection to the proxy.
Closes #405.
Please @tiero @Janaka-Steph review.
> Fix proxy connection after wallet initialization

- src/features/walletUnlocker/OnboardingConfirmMnemonic.tsx
If mnemonic is invalid show toast error but keep the phrase in input. Idea is to avoid redoing every word if the mistake was at the end.
> If mnemonic invalid show toast error but keep the phrase in input

- src/utils/connect.ts
We throw a toast error if proto is not specified. Note that it changes from original spec where we default to https if proto is not set.
> Make "proto" query param mandatory in connect url

- src/features/settings/settingsSlice.ts
- src/features/walletUnlocker/OnboardingPairing.tsx
Before this commit, there was no way the app could reach the backend daemon APIs without fixing a pathname that the [reverse proxy ](https://github.com/tdex-network/umbrel-apps/blob/tdex/tdex/caddy-data/Caddyfile) would have used.
Please @Janaka-Steph  review
> Fix packaged mode to alwyas assume /api as path for daemon APIs

- src/App.tsx
When proxy has not been started, proxyPid is undefined. Should not be part of the condition to quit app
> Fix quitting when no proxy running

- src/features/operator/operator.api.ts
- src/utils/rtk.ts
This PR prevents calling ListWithdrawals when changing strategy because of wrong RTK tags and doesn't retry OpenMarket request. 
It closes #457
> Fix performance strategy change

- src/features/operator/Market/MarketOverview/BalanceAndPrice.tsx
- src/features/operator/Market/MarketOverview/BalanceAndPriceMobile.tsx
- src/features/operator/Market/MarketOverview/CollectedSwapFees.tsx
- src/features/operator/Market/MarketOverview/VolumePanel.tsx
- src/features/operator/Market/MarketOverview/index.tsx
- src/features/operator/TxsTable/txsTable.less
Display Market balance and price when strategy pluggable on mobile
@tiero Should we add a title and tooltip? If so, I would refactor also not mobile design, having market balance and price on its own panel.
> Display Market balance and price on mobile

- src-tauri/tauri.conf.json
Should fix CI error `Unable to upload your app for notarization. --notarize-app is missing one or more required options: --asc-provider.`
> Add providerShortName to fix notarization
