tdex-network/tdex-dashboard

src/app/store.ts, src/features/operator/operator.api.ts, src/features/operator/operatorSlice.ts, src/features/settings/settingsSlice.ts
=> Operator API

src/features/home/DashboardPanelLeft.tsx, src/features/operator/operator.api.ts
=> Compute total fees earned

README.md, package.json, public/index.html, public/manifest.json
=> Rename to Tdex Dashboard

src/App.tsx
=> Add copy/paste capability with Tauri

.eslintrc.json, package.json, src/App.tsx, src/features/home/DashboardPanelLeft.tsx, src/features/home/DashboardPanelRight.tsx, src/features/operator/Market/MarketStrategy/index.tsx, src/features/operator/TxsTable/index.tsx, src/features/operator/operator.api.ts, src/features/settings/settingsSlice.ts, src/utils/timeAgo.ts, yarn.lock
Eslint config `react-app` has been moved to eslintrc and is now active. Fix resulting linting errors.
=> Lint react-app

src-tauri/src/main.rs
=> Tauri menu

src/app/config.ts, src/utils/constants.ts
Add testnet LCAD 
Fix condition
=> Fix misc testnet 

src/features/operator/Market/CreateMarket/AddCustomToken.tsx, src/features/operator/Market/CreateMarket/createMarket.less, src/features/operator/Market/CreateMarket/index.tsx, src/features/operator/operator.api.ts
=> [Generic asset] Show error when asset id incorrect

src/features/operator/Market/CreateMarket/index.tsx, src/features/operator/Market/MarketSettings/index.tsx
=> [Create Market] Add `Done` button

src/features/operator/Market/CreateMarket/index.tsx
=> After confirming a pair, changing the pair should reset all the form

src/features/operator/Market/MarketOverview/index.tsx
=> Use skeleton

src-tauri/tauri.conf.json, src/app/rootReducer.ts, src/features/operator/TxsTable/DepositRows.tsx, src/utils/storage.ts
=> Persist with Tauri FS

src/common/Shell/index.tsx, src/features/walletUnlocker/OnboardingConfirmMnemonic.tsx, src/features/walletUnlocker/OnboardingCreateOrRestore.tsx, src/features/walletUnlocker/OnboardingPairing.tsx, src/features/walletUnlocker/OnboardingRestoreMnemonic.tsx, src/features/walletUnlocker/OnboardingShowMnemonic.tsx
=> Breadcrumb onboarding pages

src/app/config.ts, src/common/SelectWithAddition/index.tsx, src/features/operator/Market/MarketFragmenterWithdraw/index.tsx, src/features/settings/ExplorersLiquidApiForm.tsx, src/features/settings/ExplorersLiquidUiForm.tsx, src/features/settings/Settings.tsx, src/features/settings/settingsSlice.ts
=> Add Liquid explorer selection in settings

src/features/operator/Fee/FeeWithdraw/feeWithdraw.less, src/features/operator/Fee/FeeWithdraw/index.tsx, src/features/operator/Market/MarketWithdraw/index.tsx, src/features/operator/Market/MarketWithdraw/marketWithdraw.less
=> Fix btc unit conversion

src/features/operator/TxsTable/TradeRows.tsx, src/features/operator/TxsTable/index.tsx
=> Fix trade transaction id

src/assets/styles/button.less, src/assets/styles/colors.less, src/assets/styles/index.less, src/features/operator/Market/MarketDeposit/index.tsx, src/features/operator/TxsTable/AllRows.tsx, src/features/operator/TxsTable/DepositRows.tsx, src/features/operator/TxsTable/TradeRows.tsx, src/features/operator/TxsTable/TxRow.tsx, src/features/operator/TxsTable/WithdrawalRows.tsx, src/features/operator/TxsTable/index.tsx, src/features/operator/operator.api.ts, src/utils/constants.ts
Refactor TxTable, add show more and server-side pagination.
It closes #104
=> Refactor TxTable, show more btn, pagination

src/common/DepositPage/depositPage.less, src/common/DepositPage/index.tsx, src/features/operator/Fee/FeeDeposit/index.tsx, src/features/operator/Market/MarketDeposit/index.tsx, src/features/operator/operator.api.ts
=> Refactor deposit page, opt-in fragmentation

src/features/operator/Fee/FeeWithdraw/index.tsx, src/features/operator/Market/MarketWithdraw/index.tsx, src/features/operator/TxsTable/AllRows.tsx, src/features/operator/TxsTable/index.tsx, src/features/settings/Settings.tsx, src/utils/asset.ts, src/utils/constants.ts, src/utils/unitConvert.ts
=> Add available and total balances in withdraw pages

src/features/operator/Market/MarketStrategy/index.tsx
=> Fix strategy selection

src/common/AnimatedEllipsis/animatedEllipsis.less, src/common/AnimatedEllipsis/index.tsx, src/common/WaitingModal/index.tsx, src/features/walletUnlocker/OnboardingRestoreMnemonic.tsx
=> Restoration waiting modal

buf.gen.yaml, buf.yaml
=> Generate stubs with Buf

src/features/operator/Fee/FeeDeposit/index.tsx, src/features/operator/Market/MarketDeposit/index.tsx, src/features/operator/operator.api.ts
=> Fee/Market deposits show progress log modal 

src/features/home/DashboardPanelLeft.tsx, src/features/operator/operator.api.ts, src/features/settings/Settings.tsx
=> Reload utxos + fix fetching totalCollectedSwapFees

src/features/operator/Fee/FeeForm/index.tsx
=> Fix reset all value disappearing

src/features/home/Home.tsx
If isReady returns an error show "Service Unavailable" modal.
Fix infinite loop SERVING / NOT_SERVING
=> If isReady returns an error show Service Unavailable modal

src/features/walletUnlocker/OnboardingConfirmMnemonic.tsx, src/features/walletUnlocker/OnboardingPairing.tsx, src/features/walletUnlocker/OnboardingRestoreMnemonic.tsx, src/features/walletUnlocker/UnlockModalForm.tsx
Send password as Buffer using default encoding UTF-8.
It closes #184 
=> Send password as Buffer

src/features/settings/Settings.tsx
=> Reset RTK apis on logout and clear cache

src/features/operator/Fee/FeeForm/index.tsx, src/features/operator/Fee/FeeWithdraw/index.tsx, src/features/operator/Market/MarketWithdraw/index.tsx
=> Use placeholders in place of 0 values

src/assets/styles/input.less, src/features/home/DashboardPanelLeft.tsx, src/features/home/DashboardPanelRight.tsx, src/features/liquid.api.ts, src/features/operator/Fee/FeeForm/index.tsx, src/features/operator/Fee/FeeWithdraw/index.tsx, src/features/operator/Market/MarketOverview/index.tsx, src/features/operator/Market/MarketWithdraw/index.tsx, src/features/operator/TxsTable/AllRows.tsx, src/features/operator/TxsTable/DepositRows.tsx, src/features/operator/TxsTable/TradeRows.tsx, src/features/operator/TxsTable/TxRow.tsx, src/features/operator/TxsTable/WithdrawalRows.tsx, src/features/operator/TxsTable/index.tsx, src/features/settings/settingsSlice.ts, src/utils/unitConvert.ts
=> Add unit in fee panel when lbtc asset + fix misc network issues

src/assets/styles/button.less, src/features/operator/Market/MarketSettings/index.tsx
=> Disable CloseMarket btn if balance not empty

src/features/operator/Market/MarketWithdraw/index.tsx
=> Fix withdraw select

src/common/Header/index.tsx
=> Remove topbar buttons

src/assets/styles/icon.less, src/assets/styles/index.less, src/domain/asset.ts, src/features/operator/Fee/FeeForm/index.tsx, src/features/operator/Market/CreateMarket/index.tsx, src/features/operator/Market/MarketOverview/AssetInfoModal.tsx, src/features/operator/Market/MarketOverview/index.tsx, src/features/operator/Market/MarketSettings/index.tsx
=> Asset info modal

src/features/operator/Fee/FeeForm/index.tsx, src/features/operator/Market/MarketOverview/index.tsx
=> Replace LBTC ticker with unit

src/features/operator/Market/MarketDeposit/index.tsx
=> Better error handling on market deposit

src/features/operator/Market/MarketOverview/index.tsx, src/features/operator/Market/MarketSettings/UpdateMarketPriceForm.tsx, src/features/operator/Market/MarketSettings/Webhook.tsx, src/features/operator/Market/MarketSettings/index.tsx, src/features/operator/Market/MarketSettings/marketSettings.less, src/features/operator/Market/MarketStrategy/index.tsx, src/utils/unitConvert.ts
=> Display and update price in Pluggable strategy

src/assets/styles/breadcrumb.less, src/assets/styles/index.less, src/common/DepositPage/index.tsx, src/features/operator/Market/MarketDeposit/index.tsx, src/features/operator/Market/MarketWithdraw/index.tsx
=> Add breadcrumb to Market Overview

src/features/operator/Market/MarketOverview/index.tsx, src/features/operator/operator.api.ts
=> Fix balance update

src/common/InputAmount/index.tsx, src/features/operator/Fee/FeeForm/index.tsx, src/features/operator/Fee/FeeWithdraw/index.tsx, src/features/operator/Market/MarketWithdraw/index.tsx, src/utils/snippets.ts, src/utils/unitConvert.ts
Introduce new component `InputAmount` that restricts input value to what is allowed according to unit.
It closes #250 
=> Withdraw inputs only accept decimal according to unit

src/features/walletUnlocker/walletUnlocker.api.ts
It may happen that the daemon returns an error Http response at 400 or 500 level and ERR_SSL_PROTOCOL_ERROR, usually after staying idle for 15 or 20 minutes.
To avoid displaying Service Unavailable popup unwantedly we retry isReady request a second after 500ms before failing.
=> Retry isReady to avoid unwanted Service Unavailable popup

src/assets/styles/button.less, src/common/DepositPage/depositPage.less, src/common/DepositPage/index.tsx, src/features/operator/Fee/FeeDeposit/index.tsx, src/features/operator/Market/MarketDeposit/index.tsx
=> Generate deposit address only on button click

.github/workflows/release-tauri.yml
Tauri beta on Mac M1 requires Rust 1.57.0
=> Install Rust 1.57.0 on CI

src/App.tsx, src/features/settings/settingsSlice.ts
Avoid losing the proxy pid after app reload
=> Persist proxy pid

src/app/config.ts, src/common/DepositPage/index.tsx, src/features/operator/Market/CreateMarket/MarketPairForm.tsx, src/features/operator/Market/CreateMarket/index.tsx, src/features/operator/Market/ListMarkets/index.tsx, src/features/operator/Market/MarketOverview/AssetInfoModal.tsx, src/features/operator/TxsTable/AllRows.tsx, src/features/operator/TxsTable/DepositRows.tsx, src/features/operator/TxsTable/TradeRows.tsx, src/features/operator/TxsTable/WithdrawalRows.tsx, src/features/operator/TxsTable/index.tsx, src/features/settings/settingsSlice.ts
=> Store assets by network

src/app/config.ts, src/features/settings/Settings.tsx, src/features/settings/settingsSlice.ts
=> Change explorers when changing network

src/features/operator/TxsTable/AllRows.tsx, src/features/operator/TxsTable/DepositRows.tsx, src/features/operator/TxsTable/TradeRows.tsx, src/features/operator/TxsTable/TxRow.tsx, src/features/operator/TxsTable/WithdrawalRows.tsx, src/features/operator/TxsTable/index.tsx, src/utils/asset.ts
Extract `getTickers()` in utils.
Fix icon in TxsTable by passing LBTC ticker and not unit.
=> GetTickers() from market. Fix icon in TxsTable

src/features/operator/TxsTable/AllRows.tsx, src/features/operator/TxsTable/TradeRows.tsx, src/features/operator/TxsTable/TxRow.tsx, src/features/operator/TxsTable/index.tsx, src/features/operator/TxsTable/txsTable.less, src/utils/timeAgo.ts
- Use requestTimeUnix instead of settleTimeUnix to compute time
- Add status column, remove status from details
- Display failure info if available or `N/A`
- Performance optimization to avoid avoidable renders
=> Handle tx failure in txs table

src/features/operator/TxsTable/TradeRows.tsx, src/features/operator/TxsTable/TxRow.tsx
- Fix table amount by checking which asset is base
- Total Value should be computed once we have price feed. For now set to base amount
=> Fix table amount by checking which asset is base

src/features/operator/operator.api.ts, src/features/wallet/wallet.api.ts, src/features/walletUnlocker/walletUnlocker.api.ts, src/utils/index.ts, src/utils/rtk.ts
Implement retry once after 500ms on all RTK requests to handle daemon returning http errors.
please review @tiero
=> Retry all RTK requests

.github/workflows/release-tauri.yml, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src-tauri/tauri.conf.json, src/App.tsx, yarn.lock
On MacOS it fixes #287 closing app from the Dock
=> Update to Tauri v1.0.0

src/features/settings/FixedAssets.tsx, src/features/settings/Settings.tsx
=> Display daemon fixed assets in Settings

src/features/walletUnlocker/walletUnlocker.api.ts
=> Refetch all on wallet unlocking

src/assets/styles/typography.less, src/common/InputAmount/index.tsx, src/features/operator/Fee/FeeWithdraw/index.tsx, src/features/operator/Market/MarketWithdraw/index.tsx, src/features/settings/Settings.tsx
=> Add confirm withdraw modals

src/features/walletUnlocker/OnboardingConfirmMnemonic.tsx, src/features/walletUnlocker/OnboardingShowMnemonic.tsx, src/features/walletUnlocker/PasswordForm.tsx
=> Disallow continuing onboarding if seed not saved

src/features/home/DashboardPanelLeft.tsx, src/features/operator/operator.api.ts, src/utils/constants.ts
=> Fix totalCollectedSwapFees

src/features/home/DashboardPanelLeft.tsx
Calculate fees as favorite currency in useEffect to avoid computation on every render
=> Calculate fees as favorite currency in useEffect

src/assets/styles/breadcrumb.less, src/assets/styles/button.less, src/assets/styles/select.less, src/common/DepositPage/index.tsx, src/common/Header/index.tsx, src/common/SelectWithAddition/index.tsx, src/common/Shell/shell.less, src/features/operator/Fee/FeeWithdraw/index.tsx, src/features/operator/Market/CreateMarket/index.tsx, src/features/operator/Market/MarketFragmenterWithdraw/index.tsx, src/features/operator/Market/MarketOverview/index.tsx, src/features/operator/Market/MarketWithdraw/index.tsx, src/features/operator/TxsTable/index.tsx, src/features/operator/TxsTable/txsTable.less, src/features/settings/DefaultCurrencyRadioButtons.tsx, src/features/settings/ExplorersLiquidApiForm.tsx, src/features/settings/ExplorersLiquidUiForm.tsx, src/features/settings/FavoriteBitcoinUnitsRadioButtons.tsx, src/features/settings/NetworkSelect.tsx, src/features/settings/Settings.tsx, src/features/walletUnlocker/OnboardingConfirmMnemonic.tsx, src/features/walletUnlocker/OnboardingCreateOrRestore.tsx, src/features/walletUnlocker/OnboardingRestoreMnemonic.tsx, src/features/walletUnlocker/OnboardingShowMnemonic.tsx
=> Settings screen

src/features/home/DashboardPanelLeft.tsx, src/features/home/DashboardPanelRight.tsx, src/features/home/Home.tsx
It closes #324 
Do not display "Fee Account Balance" and "Total Earned" amounts, only `N/A`, if network setting doesn't match the daemon's network.
=> Dont display dashboard amounts if network setting doesn't match daemon's network 

src/common/VolumeChart/index.tsx, src/features/operator/Market/MarketOverview/VolumePanel.tsx
=> Selected period volume

src/assets/styles/input.less, src/assets/styles/utilities.less, src/features/operator/Market/MarketSettings/WebhookForm.tsx, src/features/operator/Market/MarketSettings/marketSettings.less, src/features/settings/ActionButtons.tsx, src/features/settings/Settings.tsx, src/features/walletUnlocker/ChangePassword.tsx
Commented for now because of issue https://github.com/tdex-network/tdex-daemon/issues/602
=> Change password form

src/App.tsx
=> Allow connection to proxy only with cert

src/features/operator/Market/MarketOverview/VolumePanel.tsx
=> Fix price display when strategy pluggable

package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, yarn.lock
=> Update Tauri and yarn.lock

src/common/DepositPage/index.tsx
=> Hide fragmenter checkbox

src/features/walletUnlocker/OnboardingConfirmMnemonic.tsx, src/features/walletUnlocker/OnboardingShowMnemonic.tsx, src/features/walletUnlocker/onboardingConfirmMnemonic.less
Instead of removing word from bottom list when selected, word style is toggled.
=> Change UX of mnemonic verification

src/features/operator/Fee/FeeForm/index.tsx
=> Show Restart modal only if values changed

src/features/operator/Fee/FeeForm/feeForm.less, src/features/operator/Fee/FeeForm/index.tsx
=> Background on fee panel inputs

src/features/home/Home.tsx
- workaround for https://github.com/tdex-network/tdex-dashboard/issues/379
- prettier
=> fix service unavailable

src/App.tsx, src/app/store.ts, src/features/settings/settingsSlice.ts
=> Fix Service unavailable error at login

src/features/operator/Market/MarketOverview/VolumePanel.tsx, src/features/operator/Market/MarketSettings/UpdateMarketPriceForm.tsx
Update market price form takes only quote
It closes #396 
Invert visualization: `quote for 1 base`
It closes #395 
If base is btc, base is set as L-BTC unit and quote is converted accordingly.
=> Update market price form takes only quote

src-tauri/tauri.conf.json
=> Forbid resize below min size

src/features/operator/Fee/FeeDeposit/index.tsx, src/features/operator/Market/MarketDeposit/index.tsx, src/features/operator/operator.api.ts, src/features/walletUnlocker/OnboardingRestoreMnemonic.tsx, src/features/walletUnlocker/walletUnlocker.api.ts
Fix streaming calls like described here https://github.com/timostamm/protobuf-ts/blob/master/MANUAL.md#rpc-method-types
=> Fix streaming calls

src/features/settings/settingsSlice.ts, src/features/walletUnlocker/OnboardingPairing.tsx, src/utils/connect.ts
=> Connect URL validation

src/common/ConnectionIndicators/index.tsx, src/common/Header/index.tsx, src/common/HeaderOnboarding/headerOnboarding.less, src/common/HeaderOnboarding/index.tsx, src/common/Shell/index.tsx, src/common/UserMenu/index.tsx
=> Add force reset button

src/features/walletUnlocker/OnboardingConfirmMnemonic.tsx
I forgot to update this code when switching to protobuf-ts
=> Fix wallet creation

package.json, src/app/config.ts, src/domain/misc.ts, src/features/operator/Market/CreateMarket/MarketPairForm.tsx, src/features/operator/TxsTable/TradeRows.tsx, src/features/operator/TxsTable/WithdrawalRows.tsx, src/features/rates.api.ts, src/features/settings/NetworkSelect.tsx, src/features/settings/settingsSlice.ts, src/routes/index.tsx, src/utils/asset.ts, src/utils/constants.ts, yarn.lock
LDK is only used to get NetworkString type, so this PR removes it.
=> Remove LDK

src/common/DepositPage/index.tsx
=> Add text "Deposit L-BTC only"

src/App.tsx, src/features/home/Home.tsx, src/features/settings/settingsSlice.ts, src/features/walletUnlocker/OnboardingPairing.tsx, src/routes/index.tsx, src/utils/proxy.ts
In this PR we remove useProxy initial state, instead we set it when pairing
Also the retry function of startProxy has been removed
=> Refactor USE_PROXY to support CA signed TLS

src/common/WaitingModal/index.tsx
=> Make restore modal not closable

src/features/operator/Market/CreateMarket/MarketPairForm.tsx
=> Fix base or quote asset on market creation

src/features/operator/operator.api.ts, src/features/settings/settingsSlice.ts, src/features/wallet/wallet.api.ts, src/features/walletUnlocker/walletUnlocker.api.ts, src/grpcDevTool.ts
Add interceptors to make protobuf-ts to work with grpc-web-devtools extension (https://github.com/SafetyCulture/grpc-web-devtools).
Code taken from https://github.com/timostamm/protobuf-ts/issues/252#issuecomment-1129220082
=> Add interceptors so protobuf-ts work with grpc-web-devtools extension

public/index.html, src/features/settings/settingsSlice.ts, src/features/walletUnlocker/OnboardingPairing.tsx, web-entrypoint.sh
=> Replace TDEX_DAEMON_URL env var by window.location.host

public/index.html, src/assets/styles/index.less, src/assets/styles/tooltip.less, src/features/settings/Settings.tsx, web-entrypoint.sh
=> Display TRADER_HIDDEN_SERVICE env var in settings

src/features/walletUnlocker/OnboardingPairing.tsx
=> Fix baseUrl in packaged mode

src/App.tsx, src/hooks/useExponentialInterval.ts, src/utils/proxy.ts
It closes #448 
This PR doesn't fix the unknown underlying issue but fix proxy restart and effectively solve connection issue from a user perspective.
Also increase healthcheck timeout to 8s
=> Fix proxy restart + increase healthcheck timeout to 8s

src/utils/rtk.ts
Log method name on RTK failure.
=> Log method name on RTK failure

src/features/operator/TxsTable/index.tsx
=> Refactor Show more txs functionality

.github/workflows/release-tauri.yml
Update workflow file following https://github.com/tauri-apps/tauri-action readme
=> Update release-tauri GH workflow

src/assets/styles/index.less, src/assets/styles/popover.less, src/features/operator/Fee/FeeForm/index.tsx
=> Add tooltips

src/assets/styles/popover.less, src/features/operator/Fee/FeeForm/index.tsx, src/features/operator/Market/MarketOverview/CollectedSwapFees.tsx
- Add Collected Swap Fees tooltip
- On mobile fix style and trigger tooltip by click
=> Collected Swap Fees tooltip + mobile support
